/**
 * catalogSeed.ts — static list of common Norwegian groceries used to seed the item catalog.
 *
 * Exports CATALOG_SEED, ~230 real-world grocery/household items each tagged with
 * a shopping category key and a realistic Norwegian price (NOK). useCatalogStore
 * inserts these into the store_items table on first run to power autocomplete and
 * auto-categorisation, and backfills prices for any rows previously seeded without one.
 *
 * Connections:
 *   Imports → —
 *   Used by → store/useCatalogStore.ts
 *   Data    → seeds the `store_items` SQLite table (via useCatalogStore)
 *
 * Edit notes:
 *   - `category` values must match the shopping category keys (produce, dairy,
 *     meat, fish, bread, frozen, canned, dry, snacks, drinks, cleaning, personal).
 *   - Item names are intentionally Norwegian and NOT translated — only UI follows the user's language.
 *   - Prices are approximate typical NOK retail prices and will be overwritten once
 *     the user records an actual purchase via the scan/shopping flow.
 */
export type SeedItem = { name: string; category: string; price: number };

export const CATALOG_SEED: SeedItem[] = [
  // Frukt og grønt
  { name: 'Epler', category: 'produce', price: 32.90 },
  { name: 'Bananer', category: 'produce', price: 23.90 },
  { name: 'Appelsiner', category: 'produce', price: 34.90 },
  { name: 'Sitroner', category: 'produce', price: 19.90 },
  { name: 'Lime', category: 'produce', price: 14.90 },
  { name: 'Pærer', category: 'produce', price: 34.90 },
  { name: 'Druer', category: 'produce', price: 39.90 },
  { name: 'Jordbær', category: 'produce', price: 39.90 },
  { name: 'Blåbær', category: 'produce', price: 34.90 },
  { name: 'Bringebær', category: 'produce', price: 34.90 },
  { name: 'Mango', category: 'produce', price: 19.90 },
  { name: 'Avokado', category: 'produce', price: 14.90 },
  { name: 'Ananas', category: 'produce', price: 29.90 },
  { name: 'Kiwi', category: 'produce', price: 19.90 },
  { name: 'Tomater', category: 'produce', price: 29.90 },
  { name: 'Cherrytomater', category: 'produce', price: 29.90 },
  { name: 'Agurk', category: 'produce', price: 14.90 },
  { name: 'Paprika rød', category: 'produce', price: 19.90 },
  { name: 'Paprika gul', category: 'produce', price: 19.90 },
  { name: 'Paprika grønn', category: 'produce', price: 14.90 },
  { name: 'Løk', category: 'produce', price: 14.90 },
  { name: 'Rødløk', category: 'produce', price: 14.90 },
  { name: 'Hvitløk', category: 'produce', price: 14.90 },
  { name: 'Gulrøtter', category: 'produce', price: 14.90 },
  { name: 'Brokkoli', category: 'produce', price: 24.90 },
  { name: 'Blomkål', category: 'produce', price: 24.90 },
  { name: 'Salat', category: 'produce', price: 19.90 },
  { name: 'Spinat', category: 'produce', price: 24.90 },
  { name: 'Purre', category: 'produce', price: 19.90 },
  { name: 'Potet', category: 'produce', price: 29.90 },
  { name: 'Søtpotet', category: 'produce', price: 24.90 },
  { name: 'Sopp', category: 'produce', price: 24.90 },
  { name: 'Chili', category: 'produce', price: 14.90 },
  { name: 'Ingefær', category: 'produce', price: 14.90 },
  { name: 'Mais', category: 'produce', price: 14.90 },
  { name: 'Squash', category: 'produce', price: 19.90 },
  { name: 'Selleri', category: 'produce', price: 19.90 },
  { name: 'Fennikel', category: 'produce', price: 24.90 },

  // Meieri
  { name: 'Helmelk 1L', category: 'dairy', price: 26.90 },
  { name: 'Lettmelk 1L', category: 'dairy', price: 24.90 },
  { name: 'Ekstra lettmelk 1L', category: 'dairy', price: 24.90 },
  { name: 'H-melk 1L', category: 'dairy', price: 24.90 },
  { name: 'Kremfløte', category: 'dairy', price: 34.90 },
  { name: 'Matfløte', category: 'dairy', price: 29.90 },
  { name: 'Rømme', category: 'dairy', price: 27.90 },
  { name: 'Crème fraîche', category: 'dairy', price: 29.90 },
  { name: 'Kulturmelk', category: 'dairy', price: 22.90 },
  { name: 'Kefir', category: 'dairy', price: 24.90 },
  { name: 'Yoghurt naturell', category: 'dairy', price: 22.90 },
  { name: 'Gresk yoghurt', category: 'dairy', price: 29.90 },
  { name: 'Kvarg', category: 'dairy', price: 27.90 },
  { name: 'Egg 12 stk', category: 'dairy', price: 54.90 },
  { name: 'Smør', category: 'dairy', price: 49.90 },
  { name: 'Margarin', category: 'dairy', price: 34.90 },
  { name: 'Norvegia', category: 'dairy', price: 54.90 },
  { name: 'Jarlsberg', category: 'dairy', price: 59.90 },
  { name: 'Hvitost skivet', category: 'dairy', price: 44.90 },
  { name: 'Gudbrandsdalsost', category: 'dairy', price: 54.90 },
  { name: 'Brunost', category: 'dairy', price: 39.90 },
  { name: 'Fløtemysost', category: 'dairy', price: 44.90 },
  { name: 'Cheddar', category: 'dairy', price: 54.90 },
  { name: 'Mozzarella', category: 'dairy', price: 39.90 },
  { name: 'Parmesan', category: 'dairy', price: 69.90 },
  { name: 'Brie', category: 'dairy', price: 64.90 },

  // Kjøtt
  { name: 'Kyllingfilet', category: 'meat', price: 99.90 },
  { name: 'Kyllinglår', category: 'meat', price: 79.90 },
  { name: 'Kyllingkjøttdeig', category: 'meat', price: 69.90 },
  { name: 'Kjøttdeig storfe 400g', category: 'meat', price: 74.90 },
  { name: 'Lammekjøtt', category: 'meat', price: 149.90 },
  { name: 'Svinekotelett', category: 'meat', price: 79.90 },
  { name: 'Svinefilet', category: 'meat', price: 89.90 },
  { name: 'Ribbe', category: 'meat', price: 119.90 },
  { name: 'Bacon skivet', category: 'meat', price: 59.90 },
  { name: 'Grillpølser', category: 'meat', price: 49.90 },
  { name: 'Medisterpølse', category: 'meat', price: 59.90 },
  { name: 'Kjøttkaker', category: 'meat', price: 64.90 },
  { name: 'Karbonader', category: 'meat', price: 64.90 },
  { name: 'Leverpostei', category: 'meat', price: 34.90 },
  { name: 'Skinke skivet', category: 'meat', price: 44.90 },
  { name: 'Salami', category: 'meat', price: 49.90 },

  // Fisk
  { name: 'Laksefilet', category: 'fish', price: 119.90 },
  { name: 'Torskefilet', category: 'fish', price: 99.90 },
  { name: 'Ørretfilet', category: 'fish', price: 89.90 },
  { name: 'Sei filet', category: 'fish', price: 79.90 },
  { name: 'Reker', category: 'fish', price: 109.90 },
  { name: 'Tunfisk i vann', category: 'fish', price: 22.90 },
  { name: 'Makrell i tomat', category: 'fish', price: 19.90 },
  { name: 'Sild i lake', category: 'fish', price: 29.90 },
  { name: 'Fiskepinner', category: 'fish', price: 59.90 },
  { name: 'Klippfisk', category: 'fish', price: 139.90 },

  // Brød og bakst
  { name: 'Grovbrød', category: 'bread', price: 34.90 },
  { name: 'Loff', category: 'bread', price: 29.90 },
  { name: 'Kneippbrød', category: 'bread', price: 34.90 },
  { name: 'Rugbrød', category: 'bread', price: 39.90 },
  { name: 'Surdeigsbrød', category: 'bread', price: 49.90 },
  { name: 'Rundstykker', category: 'bread', price: 29.90 },
  { name: 'Bagett', category: 'bread', price: 19.90 },
  { name: 'Pitabrød', category: 'bread', price: 29.90 },
  { name: 'Tortilla hvete', category: 'bread', price: 34.90 },
  { name: 'Tortilla fullkorn', category: 'bread', price: 34.90 },
  { name: 'Hamburgerbrød', category: 'bread', price: 29.90 },
  { name: 'Hotdogbrød', category: 'bread', price: 24.90 },
  { name: 'Knekkebrød', category: 'bread', price: 39.90 },
  { name: 'Kavring', category: 'bread', price: 39.90 },
  { name: 'Flatbrød', category: 'bread', price: 34.90 },

  // Frysevarer
  { name: 'Grandiosa pizza', category: 'frozen', price: 79.90 },
  { name: 'Frosne erter', category: 'frozen', price: 24.90 },
  { name: 'Frosne bønner', category: 'frozen', price: 24.90 },
  { name: 'Frosne blandede grønnsaker', category: 'frozen', price: 29.90 },
  { name: 'Frosne spinat', category: 'frozen', price: 24.90 },
  { name: 'Frosne blåbær', category: 'frozen', price: 39.90 },
  { name: 'Frosne jordbær', category: 'frozen', price: 34.90 },
  { name: 'Pommes frites', category: 'frozen', price: 39.90 },
  { name: 'Vafler', category: 'frozen', price: 49.90 },
  { name: 'Iskrem vanilje', category: 'frozen', price: 69.90 },

  // Hermetikk
  { name: 'Hakkede tomater', category: 'canned', price: 14.90 },
  { name: 'Tomatpuré', category: 'canned', price: 19.90 },
  { name: 'Kokosmelk', category: 'canned', price: 19.90 },
  { name: 'Kikerter', category: 'canned', price: 14.90 },
  { name: 'Kidneybønner', category: 'canned', price: 14.90 },
  { name: 'Hvite bønner', category: 'canned', price: 14.90 },
  { name: 'Linser', category: 'canned', price: 14.90 },
  { name: 'Mais på boks', category: 'canned', price: 14.90 },
  { name: 'Ananas biter', category: 'canned', price: 19.90 },
  { name: 'Oliven grønne', category: 'canned', price: 24.90 },
  { name: 'Oliven sorte', category: 'canned', price: 24.90 },

  // Tørrmat
  { name: 'Spaghetti', category: 'dry', price: 19.90 },
  { name: 'Penne', category: 'dry', price: 19.90 },
  { name: 'Fusilli', category: 'dry', price: 19.90 },
  { name: 'Lasagneplater', category: 'dry', price: 24.90 },
  { name: 'Ris langkornet', category: 'dry', price: 24.90 },
  { name: 'Basmatiris', category: 'dry', price: 34.90 },
  { name: 'Havregryn', category: 'dry', price: 29.90 },
  { name: 'Müsli', category: 'dry', price: 44.90 },
  { name: 'Cornflakes', category: 'dry', price: 39.90 },
  { name: 'Hvetemel', category: 'dry', price: 19.90 },
  { name: 'Grovt mel', category: 'dry', price: 22.90 },
  { name: 'Hvitt sukker', category: 'dry', price: 19.90 },
  { name: 'Brunt sukker', category: 'dry', price: 29.90 },
  { name: 'Havsalt', category: 'dry', price: 24.90 },
  { name: 'Pepper', category: 'dry', price: 29.90 },
  { name: 'Paprikapulver', category: 'dry', price: 29.90 },
  { name: 'Karri', category: 'dry', price: 29.90 },
  { name: 'Oregano', category: 'dry', price: 24.90 },
  { name: 'Basilikum', category: 'dry', price: 24.90 },
  { name: 'Timian', category: 'dry', price: 24.90 },
  { name: 'Kanel', category: 'dry', price: 29.90 },
  { name: 'Olivenolje', category: 'dry', price: 59.90 },
  { name: 'Rapsolje', category: 'dry', price: 39.90 },
  { name: 'Soyasaus', category: 'dry', price: 34.90 },
  { name: 'Ketchup', category: 'dry', price: 29.90 },
  { name: 'Sennep', category: 'dry', price: 24.90 },
  { name: 'Majonese', category: 'dry', price: 39.90 },
  { name: 'Honning', category: 'dry', price: 59.90 },
  { name: 'Syltetøy jordbær', category: 'dry', price: 39.90 },
  { name: 'Peanøttsmør', category: 'dry', price: 49.90 },
  { name: 'Nutella', category: 'dry', price: 59.90 },
  { name: 'Kaffe malt', category: 'dry', price: 89.90 },
  { name: 'Kaffe filterkokt', category: 'dry', price: 99.90 },
  { name: 'Instant kaffe', category: 'dry', price: 79.90 },
  { name: 'Svart te', category: 'dry', price: 49.90 },
  { name: 'Grønn te', category: 'dry', price: 49.90 },
  { name: 'Kakao', category: 'dry', price: 44.90 },
  { name: 'Bakepulver', category: 'dry', price: 19.90 },
  { name: 'Tørrgjær', category: 'dry', price: 14.90 },

  // Snacks
  { name: 'Potetgull', category: 'snacks', price: 39.90 },
  { name: 'Popcorn', category: 'snacks', price: 29.90 },
  { name: 'Cashewnøtter', category: 'snacks', price: 59.90 },
  { name: 'Mandler', category: 'snacks', price: 49.90 },
  { name: 'Valnøtter', category: 'snacks', price: 59.90 },
  { name: 'Smørnøtter', category: 'snacks', price: 44.90 },
  { name: 'Pistasjenøtter', category: 'snacks', price: 64.90 },
  { name: 'Rosiner', category: 'snacks', price: 24.90 },
  { name: 'Freia melkesjokolade', category: 'snacks', price: 29.90 },
  { name: 'Kvikk Lunsj', category: 'snacks', price: 19.90 },
  { name: 'Daim', category: 'snacks', price: 34.90 },
  { name: 'KitKat', category: 'snacks', price: 19.90 },
  { name: 'Digestive kjeks', category: 'snacks', price: 34.90 },
  { name: 'Ritz kjeks', category: 'snacks', price: 34.90 },
  { name: 'Lakrisflik', category: 'snacks', price: 24.90 },
  { name: 'Twist', category: 'snacks', price: 79.90 },

  // Drikke
  { name: 'Appelsinjuice', category: 'drinks', price: 29.90 },
  { name: 'Eplejuice', category: 'drinks', price: 29.90 },
  { name: 'Smoothie', category: 'drinks', price: 39.90 },
  { name: 'Farris', category: 'drinks', price: 22.90 },
  { name: 'Imsdal', category: 'drinks', price: 19.90 },
  { name: 'Coca-Cola', category: 'drinks', price: 29.90 },
  { name: 'Pepsi Max', category: 'drinks', price: 29.90 },
  { name: 'Solo', category: 'drinks', price: 24.90 },
  { name: 'Sprite', category: 'drinks', price: 29.90 },
  { name: 'Red Bull', category: 'drinks', price: 24.90 },
  { name: 'Saft solbær', category: 'drinks', price: 34.90 },
  { name: 'Saft lime', category: 'drinks', price: 34.90 },
  { name: 'Iste', category: 'drinks', price: 24.90 },
  { name: 'Lettøl', category: 'drinks', price: 19.90 },
  { name: 'Øl', category: 'drinks', price: 24.90 },

  // Rengjøring
  { name: 'Toalettpapir', category: 'cleaning', price: 79.90 },
  { name: 'Kjøkkenrull', category: 'cleaning', price: 44.90 },
  { name: 'Husholdningsfilm', category: 'cleaning', price: 29.90 },
  { name: 'Aluminiumsfolie', category: 'cleaning', price: 29.90 },
  { name: 'Bakepapir', category: 'cleaning', price: 24.90 },
  { name: 'Søppelposer 10L', category: 'cleaning', price: 34.90 },
  { name: 'Søppelposer 20L', category: 'cleaning', price: 39.90 },
  { name: 'Søppelposer 120L', category: 'cleaning', price: 49.90 },
  { name: 'Vaskemiddel', category: 'cleaning', price: 99.90 },
  { name: 'Tøymykner', category: 'cleaning', price: 79.90 },
  { name: 'Oppvaskmiddel', category: 'cleaning', price: 39.90 },
  { name: 'Oppvasktabletter', category: 'cleaning', price: 89.90 },
  { name: 'Allrengjøring', category: 'cleaning', price: 59.90 },
  { name: 'Toalettrens', category: 'cleaning', price: 49.90 },
  { name: 'Gulvvask', category: 'cleaning', price: 59.90 },
  { name: 'Svamp', category: 'cleaning', price: 24.90 },
  { name: 'Stearinlys', category: 'cleaning', price: 39.90 },
  { name: 'Strikkeposer (frysebagger)', category: 'cleaning', price: 29.90 },

  // Personlig pleie
  { name: 'Sjampo', category: 'personal', price: 59.90 },
  { name: 'Balsam', category: 'personal', price: 59.90 },
  { name: 'Dusjgel', category: 'personal', price: 49.90 },
  { name: 'Håndsåpe', category: 'personal', price: 34.90 },
  { name: 'Deodorant', category: 'personal', price: 64.90 },
  { name: 'Tannkrem', category: 'personal', price: 44.90 },
  { name: 'Tannbørste', category: 'personal', price: 49.90 },
  { name: 'Tanntråd', category: 'personal', price: 34.90 },
  { name: 'Munnvann', category: 'personal', price: 54.90 },
  { name: 'Barberskum', category: 'personal', price: 39.90 },
  { name: 'Ansiktskrem', category: 'personal', price: 89.90 },
  { name: 'Body lotion', category: 'personal', price: 79.90 },
  { name: 'Solkrem SPF 30', category: 'personal', price: 119.90 },
  { name: 'Bind', category: 'personal', price: 54.90 },
  { name: 'Tamponger', category: 'personal', price: 59.90 },
  { name: 'Bleier', category: 'personal', price: 149.90 },
  { name: 'Bleietørk', category: 'personal', price: 64.90 },
  { name: 'Plaster', category: 'personal', price: 39.90 },
  { name: 'Paracet', category: 'personal', price: 64.90 },
  { name: 'Ibux', category: 'personal', price: 69.90 },
  { name: 'Vitaminer', category: 'personal', price: 119.90 },
  { name: 'Q-tips', category: 'personal', price: 29.90 },
];
