/**
 * catalogSeed.ts — static list of common Norwegian groceries used to seed the item catalog.
 *
 * Exports CATALOG_SEED, ~230 real-world grocery/household items each tagged with
 * a shopping category key. useCatalogStore inserts these into the store_items
 * table on first run to power autocomplete and auto-categorisation.
 *
 * Connections:
 *   Imports → —
 *   Used by → store/useCatalogStore.ts
 *   Data    → seeds the `store_items` SQLite table (via useCatalogStore)
 *
 * Edit notes:
 *   - `category` values must match the shopping category keys (produce, dairy,
 *     meat, fish, bread, frozen, canned, dry, snacks, drinks, cleaning, personal).
 *   - Item names are intentionally Norwegian and NOT translated — only UI follows the user's language.
 */
export type SeedItem = { name: string; category: string };

export const CATALOG_SEED: SeedItem[] = [
  // Frukt og grønt
  { name: 'Epler', category: 'produce' },
  { name: 'Bananer', category: 'produce' },
  { name: 'Appelsiner', category: 'produce' },
  { name: 'Sitroner', category: 'produce' },
  { name: 'Lime', category: 'produce' },
  { name: 'Pærer', category: 'produce' },
  { name: 'Druer', category: 'produce' },
  { name: 'Jordbær', category: 'produce' },
  { name: 'Blåbær', category: 'produce' },
  { name: 'Bringebær', category: 'produce' },
  { name: 'Mango', category: 'produce' },
  { name: 'Avokado', category: 'produce' },
  { name: 'Ananas', category: 'produce' },
  { name: 'Kiwi', category: 'produce' },
  { name: 'Tomater', category: 'produce' },
  { name: 'Cherrytomater', category: 'produce' },
  { name: 'Agurk', category: 'produce' },
  { name: 'Paprika rød', category: 'produce' },
  { name: 'Paprika gul', category: 'produce' },
  { name: 'Paprika grønn', category: 'produce' },
  { name: 'Løk', category: 'produce' },
  { name: 'Rødløk', category: 'produce' },
  { name: 'Hvitløk', category: 'produce' },
  { name: 'Gulrøtter', category: 'produce' },
  { name: 'Brokkoli', category: 'produce' },
  { name: 'Blomkål', category: 'produce' },
  { name: 'Salat', category: 'produce' },
  { name: 'Spinat', category: 'produce' },
  { name: 'Purre', category: 'produce' },
  { name: 'Potet', category: 'produce' },
  { name: 'Søtpotet', category: 'produce' },
  { name: 'Sopp', category: 'produce' },
  { name: 'Chili', category: 'produce' },
  { name: 'Ingefær', category: 'produce' },
  { name: 'Mais', category: 'produce' },
  { name: 'Squash', category: 'produce' },
  { name: 'Selleri', category: 'produce' },
  { name: 'Fennikel', category: 'produce' },

  // Meieri
  { name: 'Helmelk 1L', category: 'dairy' },
  { name: 'Lettmelk 1L', category: 'dairy' },
  { name: 'Ekstra lettmelk 1L', category: 'dairy' },
  { name: 'H-melk 1L', category: 'dairy' },
  { name: 'Kremfløte', category: 'dairy' },
  { name: 'Matfløte', category: 'dairy' },
  { name: 'Rømme', category: 'dairy' },
  { name: 'Crème fraîche', category: 'dairy' },
  { name: 'Kulturmelk', category: 'dairy' },
  { name: 'Kefir', category: 'dairy' },
  { name: 'Yoghurt naturell', category: 'dairy' },
  { name: 'Gresk yoghurt', category: 'dairy' },
  { name: 'Kvarg', category: 'dairy' },
  { name: 'Egg 12 stk', category: 'dairy' },
  { name: 'Smør', category: 'dairy' },
  { name: 'Margarin', category: 'dairy' },
  { name: 'Norvegia', category: 'dairy' },
  { name: 'Jarlsberg', category: 'dairy' },
  { name: 'Hvitost skivet', category: 'dairy' },
  { name: 'Gudbrandsdalsost', category: 'dairy' },
  { name: 'Brunost', category: 'dairy' },
  { name: 'Fløtemysost', category: 'dairy' },
  { name: 'Cheddar', category: 'dairy' },
  { name: 'Mozzarella', category: 'dairy' },
  { name: 'Parmesan', category: 'dairy' },
  { name: 'Brie', category: 'dairy' },

  // Kjøtt
  { name: 'Kyllingfilet', category: 'meat' },
  { name: 'Kyllinglår', category: 'meat' },
  { name: 'Kyllingkjøttdeig', category: 'meat' },
  { name: 'Kjøttdeig storfe 400g', category: 'meat' },
  { name: 'Lammekjøtt', category: 'meat' },
  { name: 'Svinekotelett', category: 'meat' },
  { name: 'Svinefilet', category: 'meat' },
  { name: 'Ribbe', category: 'meat' },
  { name: 'Bacon skivet', category: 'meat' },
  { name: 'Grillpølser', category: 'meat' },
  { name: 'Medisterpølse', category: 'meat' },
  { name: 'Kjøttkaker', category: 'meat' },
  { name: 'Karbonader', category: 'meat' },
  { name: 'Leverpostei', category: 'meat' },
  { name: 'Skinke skivet', category: 'meat' },
  { name: 'Salami', category: 'meat' },

  // Fisk
  { name: 'Laksefilet', category: 'fish' },
  { name: 'Torskefilet', category: 'fish' },
  { name: 'Ørretfilet', category: 'fish' },
  { name: 'Sei filet', category: 'fish' },
  { name: 'Reker', category: 'fish' },
  { name: 'Tunfisk i vann', category: 'fish' },
  { name: 'Makrell i tomat', category: 'fish' },
  { name: 'Sild i lake', category: 'fish' },
  { name: 'Fiskepinner', category: 'fish' },
  { name: 'Klippfisk', category: 'fish' },

  // Brød og bakst
  { name: 'Grovbrød', category: 'bread' },
  { name: 'Loff', category: 'bread' },
  { name: 'Kneippbrød', category: 'bread' },
  { name: 'Rugbrød', category: 'bread' },
  { name: 'Surdeigsbrød', category: 'bread' },
  { name: 'Rundstykker', category: 'bread' },
  { name: 'Bagett', category: 'bread' },
  { name: 'Pitabrød', category: 'bread' },
  { name: 'Tortilla hvete', category: 'bread' },
  { name: 'Tortilla fullkorn', category: 'bread' },
  { name: 'Hamburgerbrød', category: 'bread' },
  { name: 'Hotdogbrød', category: 'bread' },
  { name: 'Knekkebrød', category: 'bread' },
  { name: 'Kavring', category: 'bread' },
  { name: 'Flatbrød', category: 'bread' },

  // Frysevarer
  { name: 'Grandiosa pizza', category: 'frozen' },
  { name: 'Frosne erter', category: 'frozen' },
  { name: 'Frosne bønner', category: 'frozen' },
  { name: 'Frosne blandede grønnsaker', category: 'frozen' },
  { name: 'Frosne spinat', category: 'frozen' },
  { name: 'Frosne blåbær', category: 'frozen' },
  { name: 'Frosne jordbær', category: 'frozen' },
  { name: 'Pommes frites', category: 'frozen' },
  { name: 'Vafler', category: 'frozen' },
  { name: 'Iskrem vanilje', category: 'frozen' },

  // Hermetikk
  { name: 'Hakkede tomater', category: 'canned' },
  { name: 'Tomatpuré', category: 'canned' },
  { name: 'Kokosmelk', category: 'canned' },
  { name: 'Kikerter', category: 'canned' },
  { name: 'Kidneybønner', category: 'canned' },
  { name: 'Hvite bønner', category: 'canned' },
  { name: 'Linser', category: 'canned' },
  { name: 'Mais på boks', category: 'canned' },
  { name: 'Ananas biter', category: 'canned' },
  { name: 'Oliven grønne', category: 'canned' },
  { name: 'Oliven sorte', category: 'canned' },

  // Tørrmat
  { name: 'Spaghetti', category: 'dry' },
  { name: 'Penne', category: 'dry' },
  { name: 'Fusilli', category: 'dry' },
  { name: 'Lasagneplater', category: 'dry' },
  { name: 'Ris langkornet', category: 'dry' },
  { name: 'Basmatiris', category: 'dry' },
  { name: 'Havregryn', category: 'dry' },
  { name: 'Müsli', category: 'dry' },
  { name: 'Cornflakes', category: 'dry' },
  { name: 'Hvetemel', category: 'dry' },
  { name: 'Grovt mel', category: 'dry' },
  { name: 'Hvitt sukker', category: 'dry' },
  { name: 'Brunt sukker', category: 'dry' },
  { name: 'Havsalt', category: 'dry' },
  { name: 'Pepper', category: 'dry' },
  { name: 'Paprikapulver', category: 'dry' },
  { name: 'Karri', category: 'dry' },
  { name: 'Oregano', category: 'dry' },
  { name: 'Basilikum', category: 'dry' },
  { name: 'Timian', category: 'dry' },
  { name: 'Kanel', category: 'dry' },
  { name: 'Olivenolje', category: 'dry' },
  { name: 'Rapsolje', category: 'dry' },
  { name: 'Soyasaus', category: 'dry' },
  { name: 'Ketchup', category: 'dry' },
  { name: 'Sennep', category: 'dry' },
  { name: 'Majonese', category: 'dry' },
  { name: 'Honning', category: 'dry' },
  { name: 'Syltetøy jordbær', category: 'dry' },
  { name: 'Peanøttsmør', category: 'dry' },
  { name: 'Nutella', category: 'dry' },
  { name: 'Kaffe malt', category: 'dry' },
  { name: 'Kaffe filterkokt', category: 'dry' },
  { name: 'Instant kaffe', category: 'dry' },
  { name: 'Svart te', category: 'dry' },
  { name: 'Grønn te', category: 'dry' },
  { name: 'Kakao', category: 'dry' },
  { name: 'Bakepulver', category: 'dry' },
  { name: 'Tørrgjær', category: 'dry' },

  // Snacks
  { name: 'Potetgull', category: 'snacks' },
  { name: 'Popcorn', category: 'snacks' },
  { name: 'Cashewnøtter', category: 'snacks' },
  { name: 'Mandler', category: 'snacks' },
  { name: 'Valnøtter', category: 'snacks' },
  { name: 'Smørnøtter', category: 'snacks' },
  { name: 'Pistasjenøtter', category: 'snacks' },
  { name: 'Rosiner', category: 'snacks' },
  { name: 'Freia melkesjokolade', category: 'snacks' },
  { name: 'Kvikk Lunsj', category: 'snacks' },
  { name: 'Daim', category: 'snacks' },
  { name: 'KitKat', category: 'snacks' },
  { name: 'Digestive kjeks', category: 'snacks' },
  { name: 'Ritz kjeks', category: 'snacks' },
  { name: 'Lakrisflik', category: 'snacks' },
  { name: 'Twist', category: 'snacks' },

  // Drikke
  { name: 'Appelsinjuice', category: 'drinks' },
  { name: 'Eplejuice', category: 'drinks' },
  { name: 'Smoothie', category: 'drinks' },
  { name: 'Farris', category: 'drinks' },
  { name: 'Imsdal', category: 'drinks' },
  { name: 'Coca-Cola', category: 'drinks' },
  { name: 'Pepsi Max', category: 'drinks' },
  { name: 'Solo', category: 'drinks' },
  { name: 'Sprite', category: 'drinks' },
  { name: 'Red Bull', category: 'drinks' },
  { name: 'Saft solbær', category: 'drinks' },
  { name: 'Saft lime', category: 'drinks' },
  { name: 'Iste', category: 'drinks' },
  { name: 'Lettøl', category: 'drinks' },
  { name: 'Øl', category: 'drinks' },

  // Rengjøring
  { name: 'Toalettpapir', category: 'cleaning' },
  { name: 'Kjøkkenrull', category: 'cleaning' },
  { name: 'Husholdningsfilm', category: 'cleaning' },
  { name: 'Aluminiumsfolie', category: 'cleaning' },
  { name: 'Bakepapir', category: 'cleaning' },
  { name: 'Søppelposer 10L', category: 'cleaning' },
  { name: 'Søppelposer 20L', category: 'cleaning' },
  { name: 'Søppelposer 120L', category: 'cleaning' },
  { name: 'Vaskemiddel', category: 'cleaning' },
  { name: 'Tøymykner', category: 'cleaning' },
  { name: 'Oppvaskmiddel', category: 'cleaning' },
  { name: 'Oppvasktabletter', category: 'cleaning' },
  { name: 'Allrengjøring', category: 'cleaning' },
  { name: 'Toalettrens', category: 'cleaning' },
  { name: 'Gulvvask', category: 'cleaning' },
  { name: 'Svamp', category: 'cleaning' },
  { name: 'Stearinlys', category: 'cleaning' },
  { name: 'Strikkeposer (frysebagger)', category: 'cleaning' },

  // Personlig pleie
  { name: 'Sjampo', category: 'personal' },
  { name: 'Balsam', category: 'personal' },
  { name: 'Dusjgel', category: 'personal' },
  { name: 'Håndsåpe', category: 'personal' },
  { name: 'Deodorant', category: 'personal' },
  { name: 'Tannkrem', category: 'personal' },
  { name: 'Tannbørste', category: 'personal' },
  { name: 'Tanntråd', category: 'personal' },
  { name: 'Munnvann', category: 'personal' },
  { name: 'Barberskum', category: 'personal' },
  { name: 'Ansiktskrem', category: 'personal' },
  { name: 'Body lotion', category: 'personal' },
  { name: 'Solkrem SPF 30', category: 'personal' },
  { name: 'Bind', category: 'personal' },
  { name: 'Tamponger', category: 'personal' },
  { name: 'Bleier', category: 'personal' },
  { name: 'Bleietørk', category: 'personal' },
  { name: 'Plaster', category: 'personal' },
  { name: 'Paracet', category: 'personal' },
  { name: 'Ibux', category: 'personal' },
  { name: 'Vitaminer', category: 'personal' },
  { name: 'Q-tips', category: 'personal' },
];
